### PR TITLE
Fashros now has real ruler

### PR DESCRIPTION
**Pull request by Cilria**
Fashran DNA

### CODE REVIEW

**Comment by Cilria** [comment]
Fashrans after DNA test
all their rules are 6/5/6

:yomjack:

**Comment by u1145** [comment]
among us

**Comment by Cilria** [comment]
this is truly a Fashrans moment

**Comment by Cilria** [comment]
> among us

AMONG US AMONG US AMONG US STOP STOP STOP DING DING DING DING

**Comment by Cilria** [comment]
when added

**Comment by Cilria** [comment]
when no merge 😭

**Review by urbaxadeeznuts — CHANGES_REQUESTED** [review]
6/5/6 is too high tbh, should be around 4/4/4 range

**Comment by Cilria** [comment]
Aright I will edit it shortly to 4/3/4

**Comment by Cilria** [comment]
I have edited to 4/3/4. Can this request be done.

**Comment by Cilria** [comment]
It's been a few days. Can this be done now?

**Pull request closed without merging**
